# Split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

# Reload config file instantly with prefix + r
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Don't rename windows automatically
set-option -g allow-rename off

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Customize copy mode configurations
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# Eliminate escape key delay(for Vim user)
set -s escape-time 0

# Plugins
set -g @plugin 'dracula/tmux'

# Dracula plugin configurations
# set -g @dracula-plugins "cpu-usage gpu-usage ram-usage"
set -g @dracula-plugins "git network time"
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-left-icon-padding 1
set -g @dracula-time-format "%F %R"
set -g @dracula-show-flags true
set -g @dracula-show-fahrenheit false


# Initialize TMUX plugin manager
run "~/.tmux/plugins/tpm/tpm"
